In [3]:
import pandas
pandas.set_option("display.max_columns", None)
import numpy as np
import copy
from urllib.error import HTTPError
import matplotlib.pyplot as plt
import tqdm
import sklearn.linear_model
import sklearn.preprocessing 
import sklearn.model_selection
import sklearn.metrics

import seaborn as sns

In [1]:
startyear = 2004
endyear = 2014

***
# HOME TOV

In [5]:
TRTR = pandas.read_csv("S_Full_HoAw_" + str(startyear) + "_" + str(endyear) + ".csv")
TRTR = TRTR.loc[TRTR['GameNum'] >= 25].dropna()

coefs_b1 = []
coefs_b2 = []
for year in range(startyear, endyear + 1):
    print (year)
    TFG = copy.deepcopy(TRTR.loc[TRTR['Season'] == year])
    home_feats = TFG.loc[:,['home.GG.avg.prob_TOV', 'away.BG.avg.prob_TOV']]
    home_tar = TFG.loc[:,['home.GG.curr.prob_TOV']]
    home_Model = sklearn.linear_model.LinearRegression(fit_intercept = False).fit(home_feats, home_tar )
    TFG['pred'] = home_Model.predict(home_feats)
    print("HOME_________")
    #print(home_Model.coef_)
    coefs_b1 = coefs_b1 + [home_Model.coef_[0][0]]
    coefs_b2 = coefs_b2 + [home_Model.coef_[0][1]]
    print(sum(sum(home_Model.coef_)))
    #print ("F1 R2: " + str(np.round(sklearn.metrics.r2_score(home_tar,TFG.loc[:,['home.GG.avg.prob_TOV']]),5)))
    #print ("F2 R2: " + str((np.round(sklearn.metrics.r2_score(home_tar,TFG.loc[:,['away.BG.avg.prob_TOV']]),5))))
    print ("Yhat R2: " + str((np.round(sklearn.metrics.r2_score(home_tar, TFG['pred']),5))))
    print ("Yhat MedAE: " + str((np.round(sklearn.metrics.median_absolute_error(home_tar, TFG['pred']),5))))
    print ("Yhat MeanAE: " + str((np.round(sklearn.metrics.mean_absolute_error(home_tar, TFG['pred']),5))))
print("Coefs b1")
print(np.round(coefs_b1,5))
print("Sum Coefs b1:" + str(np.round(np.sum(coefs_b1),5)))
print("Avg Coefs b1:" + str(np.round(np.sum(coefs_b1) / (endyear - startyear + 1),5)))
print("Coefs b2")
print(np.round(coefs_b2,5))
print("Sum Coefs b2:" + str(np.round(sum(coefs_b2),5)))
print("Avg Coefs b2:" + str(np.round(np.sum(coefs_b2) / (endyear - startyear + 1),5)))
print("Avg b1 + b2 Coefs:" + str(np.round((np.sum(coefs_b2) + np.sum(coefs_b1)) / ((endyear - startyear + 1)),5)))

TFG = copy.deepcopy(TRTR)#.loc[TRTR['Season'] == year])
home_feats = TFG.loc[:,['home.GG.avg.prob_TOV', 'away.BG.avg.prob_TOV']]
home_tar = TFG.loc[:,['home.GG.curr.prob_TOV']]
home_Model = sklearn.linear_model.LinearRegression(fit_intercept = False).fit(home_feats, home_tar )
TFG['pred'] = home_Model.predict(home_feats)
print("ALL_________")
print(home_Model.coef_)
# coefs_b1 = coefs_b1 + [home_Model.coef_[0][0]]
# coefs_b2 = coefs_b2 + [home_Model.coef_[0][1]]
print(sum(sum(home_Model.coef_)))
#print ("F1 R2: " + str(np.round(sklearn.metrics.r2_score(home_tar,TFG.loc[:,['home.GG.avg.prob_TOV']]),5)))
#print ("F2 R2: " + str((np.round(sklearn.metrics.r2_score(home_tar,TFG.loc[:,['away.BG.avg.prob_TOV']]),5))))
print ("Yhat R2: " + str((np.round(sklearn.metrics.r2_score(home_tar, TFG['pred']),5))))
print ("Yhat MedAE: " + str((np.round(sklearn.metrics.median_absolute_error(home_tar, TFG['pred']),5))))
print ("Yhat MeanAE: " + str((np.round(sklearn.metrics.mean_absolute_error(home_tar, TFG['pred']),5))))

2004
HOME_________
0.9710034504098366
Yhat R2: 0.09101
Yhat MedAE: 0.02321
Yhat MeanAE: 0.02684
2005
HOME_________
0.9549810480031296
Yhat R2: 0.10819
Yhat MedAE: 0.02199
Yhat MeanAE: 0.02501
2006
HOME_________
0.9664962895923508
Yhat R2: 0.076
Yhat MedAE: 0.02162
Yhat MeanAE: 0.02535
2007
HOME_________
0.960401757368139
Yhat R2: 0.04225
Yhat MedAE: 0.02232
Yhat MeanAE: 0.0265
2008
HOME_________
0.9252341559349154
Yhat R2: 0.0794
Yhat MedAE: 0.0216
Yhat MeanAE: 0.0249
2009
HOME_________
0.9513952243473873
Yhat R2: 0.07932
Yhat MedAE: 0.02151
Yhat MeanAE: 0.02544
2010
HOME_________
0.9515338011309558
Yhat R2: 0.05555
Yhat MedAE: 0.02156
Yhat MeanAE: 0.02584
2011
HOME_________
0.9545328073857395
Yhat R2: 0.05609
Yhat MedAE: 0.02242
Yhat MeanAE: 0.02569
2012
HOME_________
0.9536308886212218
Yhat R2: 0.09167
Yhat MedAE: 0.021
Yhat MeanAE: 0.02482
2013
HOME_________
0.9772252722780508
Yhat R2: 0.03544
Yhat MedAE: 0.02102
Yhat MeanAE: 0.02538
2014
HOME_________
0.9618090078274173
Yhat R2: 0.

***
# Away TOV

In [6]:
TRTR = pandas.read_csv("S_Full_HoAw_" + str(startyear) + "_" + str(endyear) + ".csv")
TRTR = TRTR.loc[TRTR['GameNum'] >= 25].dropna()

coefs_b1 = []
coefs_b2 = []
for year in range(startyear, endyear + 1):
    print (year)
    TFG = copy.deepcopy(TRTR.loc[TRTR['Season'] == year])
    away_feats = TFG.loc[:,['away.GG.avg.prob_TOV', 'home.BG.avg.prob_TOV']]
    away_tar = TFG.loc[:,['away.GG.curr.prob_TOV']]
    away_Model = sklearn.linear_model.LinearRegression(fit_intercept = False).fit(away_feats, away_tar )
    TFG['pred'] = away_Model.predict(away_feats)
    print("away_________")
    #print(away_Model.coef_)
    coefs_b1 = coefs_b1 + [away_Model.coef_[0][0]]
    coefs_b2 = coefs_b2 + [away_Model.coef_[0][1]]
    print(sum(sum(away_Model.coef_)))
    #print ("F1 R2: " + str(np.round(sklearn.metrics.r2_score(away_tar,TFG.loc[:,['away.GG.avg.prob_TOV']]),5)))
    #print ("F2 R2: " + str((np.round(sklearn.metrics.r2_score(away_tar,TFG.loc[:,['away.BG.avg.prob_TOV']]),5))))
    print ("Yhat R2: " + str((np.round(sklearn.metrics.r2_score(away_tar, TFG['pred']),5))))
    print ("Yhat MedAE: " + str((np.round(sklearn.metrics.median_absolute_error(away_tar, TFG['pred']),5))))
    print ("Yhat MeanAE: " + str((np.round(sklearn.metrics.mean_absolute_error(away_tar, TFG['pred']),5))))
print("Coefs b1")
print(np.round(coefs_b1,5))
print("Sum Coefs b1:" + str(np.round(np.sum(coefs_b1),5)))
print("Avg Coefs b1:" + str(np.round(np.sum(coefs_b1) / (endyear - startyear + 1),5)))
print("Coefs b2")
print(np.round(coefs_b2,5))
print("Sum Coefs b2:" + str(np.round(sum(coefs_b2),5)))
print("Avg Coefs b2:" + str(np.round(np.sum(coefs_b2) / (endyear - startyear + 1),5)))
print("Avg b1 + b2 Coefs:" + str(np.round((np.sum(coefs_b2) + np.sum(coefs_b1)) / ((endyear - startyear + 1)),5)))

TFG = copy.deepcopy(TRTR)
away_feats = TFG.loc[:,['away.GG.avg.prob_TOV', 'home.BG.avg.prob_TOV']]
away_tar = TFG.loc[:,['away.GG.curr.prob_TOV']]
away_Model = sklearn.linear_model.LinearRegression(fit_intercept = False).fit(away_feats, away_tar )
TFG['pred'] = away_Model.predict(away_feats)
print("away_________")
print(away_Model.coef_)
# coefs_b1 = coefs_b1 + [away_Model.coef_[0][0]]
# coefs_b2 = coefs_b2 + [away_Model.coef_[0][1]]
print(sum(sum(away_Model.coef_)))
#print ("F1 R2: " + str(np.round(sklearn.metrics.r2_score(away_tar,TFG.loc[:,['away.GG.avg.prob_TOV']]),5)))
#print ("F2 R2: " + str((np.round(sklearn.metrics.r2_score(away_tar,TFG.loc[:,['away.BG.avg.prob_TOV']]),5))))
print ("Yhat R2: " + str((np.round(sklearn.metrics.r2_score(away_tar, TFG['pred']),5))))
print ("Yhat MedAE: " + str((np.round(sklearn.metrics.median_absolute_error(away_tar, TFG['pred']),5))))
print ("Yhat MeanAE: " + str((np.round(sklearn.metrics.mean_absolute_error(away_tar, TFG['pred']),5))))

2004
away_________
1.0043775170495695
Yhat R2: 0.11082
Yhat MedAE: 0.02299
Yhat MeanAE: 0.02704
2005
away_________
0.9706923436927963
Yhat R2: 0.0962
Yhat MedAE: 0.02185
Yhat MeanAE: 0.02629
2006
away_________
1.0085441993483852
Yhat R2: 0.07692
Yhat MedAE: 0.0222
Yhat MeanAE: 0.02693
2007
away_________
0.99041314491555
Yhat R2: 0.05096
Yhat MedAE: 0.02382
Yhat MeanAE: 0.02751
2008
away_________
0.9677130601797747
Yhat R2: 0.09158
Yhat MedAE: 0.0221
Yhat MeanAE: 0.02687
2009
away_________
0.9845452845413288
Yhat R2: 0.10589
Yhat MedAE: 0.0226
Yhat MeanAE: 0.02689
2010
away_________
0.9864277857227757
Yhat R2: 0.07615
Yhat MedAE: 0.02157
Yhat MeanAE: 0.02519
2011
away_________
0.9952156078003046
Yhat R2: 0.06752
Yhat MedAE: 0.02171
Yhat MeanAE: 0.0261
2012
away_________
0.9753389049407029
Yhat R2: 0.08945
Yhat MedAE: 0.02203
Yhat MeanAE: 0.02606
2013
away_________
0.9996769461315704
Yhat R2: 0.05335
Yhat MedAE: 0.02182
Yhat MeanAE: 0.02592
2014
away_________
0.9751335366028144
Yhat R2: 

***
# HOME FTA

In [5]:
TRTR = pandas.read_csv("S_Full_HoAw_" + str(startyear) + "_" + str(endyear) + ".csv")
TRTR = TRTR.loc[TRTR['GameNum'] >= 25].dropna()

coefs_b1 = []
coefs_b2 = []
for year in range(startyear, endyear + 1):
    print (year)
    TFG = copy.deepcopy(TRTR.loc[TRTR['Season'] == year])
    home_feats = TFG.loc[:,['home.GG.avg.prob_FT', 'away.BG.avg.prob_FT']]
    home_tar = TFG.loc[:,['home.GG.curr.prob_FT']]
    home_Model = sklearn.linear_model.LinearRegression(fit_intercept = False).fit(home_feats, home_tar )
    TFG['pred'] = home_Model.predict(home_feats)
    print("HOME_________")
    #print(home_Model.coef_)
    coefs_b1 = coefs_b1 + [home_Model.coef_[0][0]]
    coefs_b2 = coefs_b2 + [home_Model.coef_[0][1]]
    print(sum(sum(home_Model.coef_)))
    #print ("F1 R2: " + str(np.round(sklearn.metrics.r2_score(home_tar,TFG.loc[:,['home.GG.avg.prob_FT']]),5)))
    #print ("F2 R2: " + str((np.round(sklearn.metrics.r2_score(home_tar,TFG.loc[:,['away.BG.avg.prob_FT']]),5))))
    print ("Yhat R2: " + str((np.round(sklearn.metrics.r2_score(home_tar, TFG['pred']),5))))
    print ("Yhat MedAE: " + str((np.round(sklearn.metrics.median_absolute_error(home_tar, TFG['pred']),5))))
    print ("Yhat MeanAE: " + str((np.round(sklearn.metrics.mean_absolute_error(home_tar, TFG['pred']),5))))
print("Coefs b1")
print(np.round(coefs_b1,5))
print("Sum Coefs b1:" + str(np.round(np.sum(coefs_b1),5)))
print("Avg Coefs b1:" + str(np.round(np.sum(coefs_b1) / (endyear - startyear + 1),5)))
print("Coefs b2")
print(np.round(coefs_b2,5))
print("Sum Coefs b2:" + str(np.round(sum(coefs_b2),5)))
print("Avg Coefs b2:" + str(np.round(np.sum(coefs_b2) / (endyear - startyear + 1),5)))
print("Avg b1 + b2 Coefs:" + str(np.round((np.sum(coefs_b2) + np.sum(coefs_b1)) / ((endyear - startyear + 1)),5)))


2006
HOME_________
1.023503912449521
Yhat R2: 0.11268
Yhat MedAE: 0.02454
Yhat MeanAE: 0.02874
2007
HOME_________
1.0109260669725022
Yhat R2: 0.11274
Yhat MedAE: 0.02381
Yhat MeanAE: 0.02794
2008
HOME_________
1.007869198303018
Yhat R2: 0.11998
Yhat MedAE: 0.02247
Yhat MeanAE: 0.02569
2009
HOME_________
1.0204527046548897
Yhat R2: 0.09652
Yhat MedAE: 0.02272
Yhat MeanAE: 0.02592
2010
HOME_________
1.0095869283587315
Yhat R2: 0.10576
Yhat MedAE: 0.01992
Yhat MeanAE: 0.02414
2011
HOME_________
0.9985161170463125
Yhat R2: 0.08525
Yhat MedAE: 0.02102
Yhat MeanAE: 0.02544
2012
HOME_________
1.0188278281543617
Yhat R2: 0.08528
Yhat MedAE: 0.02206
Yhat MeanAE: 0.02559
2013
HOME_________
1.0128302193685297
Yhat R2: 0.10985
Yhat MedAE: 0.02086
Yhat MeanAE: 0.02537
2014
HOME_________
1.0357840883143643
Yhat R2: 0.11322
Yhat MedAE: 0.02109
Yhat MeanAE: 0.02556
Coefs b1
[0.49293 0.53143 0.39671 0.47632 0.50833 0.62659 0.39645 0.62366 0.62371]
Sum Coefs b1:4.67614
Avg Coefs b1:0.51957
Coefs b2
[0.5

***
# Away FTA

In [6]:
TRTR = pandas.read_csv("S_Full_HoAw_" + str(startyear) + "_" + str(endyear) + ".csv")
TRTR = TRTR.loc[TRTR['GameNum'] >= 25].dropna()

coefs_b1 = []
coefs_b2 = []
for year in range(startyear, endyear + 1):
    print (year)
    TFG = copy.deepcopy(TRTR.loc[TRTR['Season'] == year])
    away_feats = TFG.loc[:,['away.GG.avg.prob_FT', 'home.BG.avg.prob_FT']]
    away_tar = TFG.loc[:,['away.GG.curr.prob_FT']]
    away_Model = sklearn.linear_model.LinearRegression(fit_intercept = False).fit(away_feats, away_tar )
    TFG['pred'] = away_Model.predict(away_feats)
    print("away_________")
    #print(away_Model.coef_)
    coefs_b1 = coefs_b1 + [away_Model.coef_[0][0]]
    coefs_b2 = coefs_b2 + [away_Model.coef_[0][1]]
    print(sum(sum(away_Model.coef_)))
    #print ("F1 R2: " + str(np.round(sklearn.metrics.r2_score(away_tar,TFG.loc[:,['away.GG.avg.prob_FT']]),5)))
    #print ("F2 R2: " + str((np.round(sklearn.metrics.r2_score(away_tar,TFG.loc[:,['away.BG.avg.prob_FT']]),5))))
    print ("Yhat R2: " + str((np.round(sklearn.metrics.r2_score(away_tar, TFG['pred']),5))))
    print ("Yhat MedAE: " + str((np.round(sklearn.metrics.median_absolute_error(away_tar, TFG['pred']),5))))
    print ("Yhat MeanAE: " + str((np.round(sklearn.metrics.mean_absolute_error(away_tar, TFG['pred']),5))))
print("Coefs b1")
print(np.round(coefs_b1,5))
print("Sum Coefs b1:" + str(np.round(np.sum(coefs_b1),5)))
print("Avg Coefs b1:" + str(np.round(np.sum(coefs_b1) / (endyear - startyear + 1),5)))
print("Coefs b2")
print(np.round(coefs_b2,5))
print("Sum Coefs b2:" + str(np.round(sum(coefs_b2),5)))
print("Avg Coefs b2:" + str(np.round(np.sum(coefs_b2) / (endyear - startyear + 1),5)))
print("Avg b1 + b2 Coefs:" + str(np.round((np.sum(coefs_b2) + np.sum(coefs_b1)) / ((endyear - startyear + 1)),5)))

2006
away_________
0.9693844188595302
Yhat R2: 0.11445
Yhat MedAE: 0.02205
Yhat MeanAE: 0.02706
2007
away_________
0.9693106359576125
Yhat R2: 0.09136
Yhat MedAE: 0.0218
Yhat MeanAE: 0.02606
2008
away_________
0.9680229151852493
Yhat R2: 0.13354
Yhat MedAE: 0.02135
Yhat MeanAE: 0.02465
2009
away_________
0.9717578760358594
Yhat R2: 0.0883
Yhat MedAE: 0.02263
Yhat MeanAE: 0.02584
2010
away_________
0.9723696717954633
Yhat R2: 0.08564
Yhat MedAE: 0.02033
Yhat MeanAE: 0.0241
2011
away_________
0.950721635851216
Yhat R2: 0.05946
Yhat MedAE: 0.02038
Yhat MeanAE: 0.025
2012
away_________
0.9623065484664897
Yhat R2: 0.088
Yhat MedAE: 0.02043
Yhat MeanAE: 0.02387
2013
away_________
0.967736559768247
Yhat R2: 0.11512
Yhat MedAE: 0.02055
Yhat MeanAE: 0.02406
2014
away_________
0.9968559459114699
Yhat R2: 0.09852
Yhat MedAE: 0.0202
Yhat MeanAE: 0.02374
Coefs b1
[0.56269 0.39121 0.41353 0.40183 0.54672 0.4956  0.4476  0.70388 0.52166]
Sum Coefs b1:4.48472
Avg Coefs b1:0.4983
Coefs b2
[0.4067  0.57

***
# HOME Prob 3 given FG

In [7]:
TRTR = pandas.read_csv("S_Full_HoAw_" + str(startyear) + "_" + str(endyear) + ".csv")
TRTR = TRTR.loc[TRTR['GameNum'] >= 25].dropna()

coefs_b1 = []
coefs_b2 = []
for year in range(startyear, endyear + 1):
    print (year)
    T3p_gFG = copy.deepcopy(TRTR.loc[TRTR['Season'] == year])
    home_feats = T3p_gFG.loc[:,['home.GG.avg.prob_3p_gFG', 'away.BG.avg.prob_3p_gFG']]
    home_tar = T3p_gFG.loc[:,['home.GG.curr.prob_3p_gFG']]
    home_Model = sklearn.linear_model.LinearRegression(fit_intercept = False).fit(home_feats, home_tar )
    T3p_gFG['pred'] = home_Model.predict(home_feats)
    print("HOME_________")
    #print(home_Model.coef_)
    coefs_b1 = coefs_b1 + [home_Model.coef_[0][0]]
    coefs_b2 = coefs_b2 + [home_Model.coef_[0][1]]
    print(sum(sum(home_Model.coef_)))
    #print ("F1 R2: " + str(np.round(sklearn.metrics.r2_score(home_tar,T3p_gFG.loc[:,['home.GG.avg.prob_3p_gFG']]),5)))
    #print ("F2 R2: " + str((np.round(sklearn.metrics.r2_score(home_tar,T3p_gFG.loc[:,['away.BG.avg.prob_3p_gFG']]),5))))
    print ("Yhat R2: " + str((np.round(sklearn.metrics.r2_score(home_tar, T3p_gFG['pred']),5))))
    print ("Yhat MedAE: " + str((np.round(sklearn.metrics.median_absolute_error(home_tar, T3p_gFG['pred']),5))))
    print ("Yhat MeanAE: " + str((np.round(sklearn.metrics.mean_absolute_error(home_tar, T3p_gFG['pred']),5))))
print("Coefs b1")
print(np.round(coefs_b1,5))
print("Sum Coefs b1:" + str(np.round(np.sum(coefs_b1),5)))
print("Avg Coefs b1:" + str(np.round(np.sum(coefs_b1) / (endyear - startyear + 1),5)))
print("Coefs b2")
print(np.round(coefs_b2,5))
print("Sum Coefs b2:" + str(np.round(sum(coefs_b2),5)))
print("Avg Coefs b2:" + str(np.round(np.sum(coefs_b2) / (endyear - startyear + 1),5)))
print("Avg b1 + b2 Coefs:" + str(np.round((np.sum(coefs_b2) + np.sum(coefs_b1)) / ((endyear - startyear + 1)),5)))


2006
HOME_________
1.040113369687068
Yhat R2: 0.35546
Yhat MedAE: 0.03972
Yhat MeanAE: 0.04622
2007
HOME_________
1.0112378715524875
Yhat R2: 0.31668
Yhat MedAE: 0.04021
Yhat MeanAE: 0.04736
2008
HOME_________
1.0142662989426006
Yhat R2: 0.34397
Yhat MedAE: 0.03787
Yhat MeanAE: 0.04542
2009
HOME_________
1.0049966339330587
Yhat R2: 0.32204
Yhat MedAE: 0.03885
Yhat MeanAE: 0.04684
2010
HOME_________
1.006218462197059
Yhat R2: 0.35287
Yhat MedAE: 0.03727
Yhat MeanAE: 0.04304
2011
HOME_________
1.0072578573167266
Yhat R2: 0.33501
Yhat MedAE: 0.04039
Yhat MeanAE: 0.04628
2012
HOME_________
1.013200197863433
Yhat R2: 0.37357
Yhat MedAE: 0.03639
Yhat MeanAE: 0.04477
2013
HOME_________
1.0064269007566946
Yhat R2: 0.34894
Yhat MedAE: 0.03821
Yhat MeanAE: 0.04522
2014
HOME_________
1.0226080747191086
Yhat R2: 0.30502
Yhat MedAE: 0.04119
Yhat MeanAE: 0.04736
Coefs b1
[0.7549  0.83313 0.80928 0.72294 0.73045 0.85033 0.87161 0.79313 0.73563]
Sum Coefs b1:7.10138
Avg Coefs b1:0.78904
Coefs b2
[0.28

***
# Away Prob 3 Given FG

In [8]:
TRTR = pandas.read_csv("S_Full_HoAw_" + str(startyear) + "_" + str(endyear) + ".csv")
TRTR = TRTR.loc[TRTR['GameNum'] >= 25].dropna()

coefs_b1 = []
coefs_b2 = []
for year in range(startyear, endyear + 1):
    print (year)
    TFG = copy.deepcopy(TRTR.loc[TRTR['Season'] == year])
    away_feats = TFG.loc[:,['away.GG.avg.prob_3p_gFG', 'home.BG.avg.prob_3p_gFG']]
    away_tar = TFG.loc[:,['away.GG.curr.prob_3p_gFG']]
    away_Model = sklearn.linear_model.LinearRegression(fit_intercept = False).fit(away_feats, away_tar )
    TFG['pred'] = away_Model.predict(away_feats)
    print("away_________")
    #print(away_Model.coef_)
    coefs_b1 = coefs_b1 + [away_Model.coef_[0][0]]
    coefs_b2 = coefs_b2 + [away_Model.coef_[0][1]]
    print(sum(sum(away_Model.coef_)))
    #print ("F1 R2: " + str(np.round(sklearn.metrics.r2_score(away_tar,TFG.loc[:,['away.GG.avg.prob_3p_gFG']]),5)))
    #print ("F2 R2: " + str((np.round(sklearn.metrics.r2_score(away_tar,TFG.loc[:,['away.BG.avg.prob_3p_gFG']]),5))))
    print ("Yhat R2: " + str((np.round(sklearn.metrics.r2_score(away_tar, TFG['pred']),5))))
    print ("Yhat MedAE: " + str((np.round(sklearn.metrics.median_absolute_error(away_tar, TFG['pred']),5))))
    print ("Yhat MeanAE: " + str((np.round(sklearn.metrics.mean_absolute_error(away_tar, TFG['pred']),5))))
print("Coefs b1")
print(np.round(coefs_b1,5))
print("Sum Coefs b1:" + str(np.round(np.sum(coefs_b1),5)))
print("Avg Coefs b1:" + str(np.round(np.sum(coefs_b1) / (endyear - startyear + 1),5)))
print("Coefs b2")
print(np.round(coefs_b2,5))
print("Sum Coefs b2:" + str(np.round(sum(coefs_b2),5)))
print("Avg Coefs b2:" + str(np.round(np.sum(coefs_b2) / (endyear - startyear + 1),5)))
print("Avg b1 + b2 Coefs:" + str(np.round((np.sum(coefs_b2) + np.sum(coefs_b1)) / ((endyear - startyear + 1)),5)))

2006
away_________
1.0552433752516257
Yhat R2: 0.34896
Yhat MedAE: 0.03935
Yhat MeanAE: 0.04537
2007
away_________
1.0196744737836119
Yhat R2: 0.30955
Yhat MedAE: 0.0398
Yhat MeanAE: 0.04691
2008
away_________
1.0180470473685674
Yhat R2: 0.35594
Yhat MedAE: 0.04034
Yhat MeanAE: 0.04703
2009
away_________
1.0194771024601421
Yhat R2: 0.3498
Yhat MedAE: 0.03702
Yhat MeanAE: 0.04527
2010
away_________
1.022975871721494
Yhat R2: 0.36644
Yhat MedAE: 0.0381
Yhat MeanAE: 0.04427
2011
away_________
0.9930882554194442
Yhat R2: 0.38811
Yhat MedAE: 0.03701
Yhat MeanAE: 0.04406
2012
away_________
1.0185637796397877
Yhat R2: 0.37738
Yhat MedAE: 0.03478
Yhat MeanAE: 0.04271
2013
away_________
1.0246023321837134
Yhat R2: 0.33967
Yhat MedAE: 0.04037
Yhat MeanAE: 0.04752
2014
away_________
1.0366840078276482
Yhat R2: 0.27595
Yhat MedAE: 0.04339
Yhat MeanAE: 0.04947
Coefs b1
[0.74817 0.81102 0.7943  0.78938 0.82582 0.94471 0.79201 0.77539 0.74969]
Sum Coefs b1:7.23049
Avg Coefs b1:0.80339
Coefs b2
[0.307

***
# HOME 2 make

In [9]:
TRTR = pandas.read_csv("S_Full_HoAw_" + str(startyear) + "_" + str(endyear) + ".csv")
TRTR = TRTR.loc[TRTR['GameNum'] >= 25].dropna()

coefs_b1 = []
coefs_b2 = []
for year in range(startyear, endyear + 1):
    print (year)
    T2make = copy.deepcopy(TRTR.loc[TRTR['Season'] == year])
    home_feats = T2make.loc[:,['home.GG.avg.prob_2make', 'away.BG.avg.prob_2make']]
    home_tar = T2make.loc[:,['home.GG.curr.prob_2make']]
    home_Model = sklearn.linear_model.LinearRegression(fit_intercept = False).fit(home_feats, home_tar )
    T2make['pred'] = home_Model.predict(home_feats)
    print("HOME_________")
    #print(home_Model.coef_)
    coefs_b1 = coefs_b1 + [home_Model.coef_[0][0]]
    coefs_b2 = coefs_b2 + [home_Model.coef_[0][1]]
    print(sum(sum(home_Model.coef_)))
    #print ("F1 R2: " + str(np.round(sklearn.metrics.r2_score(home_tar,T2make.loc[:,['home.GG.avg.prob_2make']]),5)))
    #print ("F2 R2: " + str((np.round(sklearn.metrics.r2_score(home_tar,T2make.loc[:,['away.BG.avg.prob_2make']]),5))))
    print ("Yhat R2: " + str((np.round(sklearn.metrics.r2_score(home_tar, T2make['pred']),5))))
    print ("Yhat MedAE: " + str((np.round(sklearn.metrics.median_absolute_error(home_tar, T2make['pred']),5))))
    print ("Yhat MeanAE: " + str((np.round(sklearn.metrics.mean_absolute_error(home_tar, T2make['pred']),5))))
print("Coefs b1")
print(np.round(coefs_b1,5))
print("Sum Coefs b1:" + str(np.round(np.sum(coefs_b1),5)))
print("Avg Coefs b1:" + str(np.round(np.sum(coefs_b1) / (endyear - startyear + 1),5)))
print("Coefs b2")
print(np.round(coefs_b2,5))
print("Sum Coefs b2:" + str(np.round(sum(coefs_b2),5)))
print("Avg Coefs b2:" + str(np.round(np.sum(coefs_b2) / (endyear - startyear + 1),5)))
print("Avg b1 + b2 Coefs:" + str(np.round((np.sum(coefs_b2) + np.sum(coefs_b1)) / ((endyear - startyear + 1)),5)))


2006
HOME_________
1.0350903381858008
Yhat R2: 0.09146
Yhat MedAE: 0.04185
Yhat MeanAE: 0.04943
2007
HOME_________
1.017223779277166
Yhat R2: 0.0674
Yhat MedAE: 0.04274
Yhat MeanAE: 0.05155
2008
HOME_________
1.0297471564284508
Yhat R2: 0.08703
Yhat MedAE: 0.04064
Yhat MeanAE: 0.04968
2009
HOME_________
1.0281748601316216
Yhat R2: 0.06779
Yhat MedAE: 0.04096
Yhat MeanAE: 0.0485
2010
HOME_________
1.0232464541373933
Yhat R2: 0.10044
Yhat MedAE: 0.04535
Yhat MeanAE: 0.05217
2011
HOME_________
1.0261749112924974
Yhat R2: 0.08728
Yhat MedAE: 0.04353
Yhat MeanAE: 0.04986
2012
HOME_________
1.0250273838207684
Yhat R2: 0.07091
Yhat MedAE: 0.04567
Yhat MeanAE: 0.05327
2013
HOME_________
1.0358917227019935
Yhat R2: 0.13313
Yhat MedAE: 0.04217
Yhat MeanAE: 0.05062
2014
HOME_________
1.0363655639592215
Yhat R2: 0.11091
Yhat MedAE: 0.0435
Yhat MeanAE: 0.05116
Coefs b1
[0.4036  0.57859 0.55486 0.42881 0.47729 0.66092 0.60686 0.64683 0.67899]
Sum Coefs b1:5.03675
Avg Coefs b1:0.55964
Coefs b2
[0.631

***
# Away 2Make

In [10]:
TRTR = pandas.read_csv("S_Full_HoAw_" + str(startyear) + "_" + str(endyear) + ".csv")
TRTR = TRTR.loc[TRTR['GameNum'] >= 25].dropna()

coefs_b1 = []
coefs_b2 = []
for year in range(startyear, endyear + 1):
    print (year)
    TFG = copy.deepcopy(TRTR.loc[TRTR['Season'] == year])
    away_feats = TFG.loc[:,['away.GG.avg.prob_2make', 'home.BG.avg.prob_2make']]
    away_tar = TFG.loc[:,['away.GG.curr.prob_2make']]
    away_Model = sklearn.linear_model.LinearRegression(fit_intercept = False).fit(away_feats, away_tar )
    TFG['pred'] = away_Model.predict(away_feats)
    print("away_________")
    #print(away_Model.coef_)
    coefs_b1 = coefs_b1 + [away_Model.coef_[0][0]]
    coefs_b2 = coefs_b2 + [away_Model.coef_[0][1]]
    print(sum(sum(away_Model.coef_)))
    #print ("F1 R2: " + str(np.round(sklearn.metrics.r2_score(away_tar,TFG.loc[:,['away.GG.avg.prob_2make']]),5)))
    #print ("F2 R2: " + str((np.round(sklearn.metrics.r2_score(away_tar,TFG.loc[:,['away.BG.avg.prob_2make']]),5))))
    print ("Yhat R2: " + str((np.round(sklearn.metrics.r2_score(away_tar, TFG['pred']),5))))
    print ("Yhat MedAE: " + str((np.round(sklearn.metrics.median_absolute_error(away_tar, TFG['pred']),5))))
    print ("Yhat MeanAE: " + str((np.round(sklearn.metrics.mean_absolute_error(away_tar, TFG['pred']),5))))
print("Coefs b1")
print(np.round(coefs_b1,5))
print("Sum Coefs b1:" + str(np.round(np.sum(coefs_b1),5)))
print("Avg Coefs b1:" + str(np.round(np.sum(coefs_b1) / (endyear - startyear + 1),5)))
print("Coefs b2")
print(np.round(coefs_b2,5))
print("Sum Coefs b2:" + str(np.round(sum(coefs_b2),5)))
print("Avg Coefs b2:" + str(np.round(np.sum(coefs_b2) / (endyear - startyear + 1),5)))
print("Avg b1 + b2 Coefs:" + str(np.round((np.sum(coefs_b2) + np.sum(coefs_b1)) / ((endyear - startyear + 1)),5)))

2006
away_________
1.0030152477438126
Yhat R2: 0.08319
Yhat MedAE: 0.03994
Yhat MeanAE: 0.04939
2007
away_________
0.9922834691905598
Yhat R2: 0.04528
Yhat MedAE: 0.04301
Yhat MeanAE: 0.05074
2008
away_________
0.9983451745178187
Yhat R2: 0.086
Yhat MedAE: 0.04372
Yhat MeanAE: 0.05122
2009
away_________
0.9983869540399382
Yhat R2: 0.05984
Yhat MedAE: 0.04101
Yhat MeanAE: 0.0501
2010
away_________
1.0003629857346623
Yhat R2: 0.05534
Yhat MedAE: 0.04082
Yhat MeanAE: 0.04971
2011
away_________
0.9977115796532504
Yhat R2: 0.05389
Yhat MedAE: 0.04114
Yhat MeanAE: 0.04944
2012
away_________
0.998475135255342
Yhat R2: 0.07035
Yhat MedAE: 0.04097
Yhat MeanAE: 0.0487
2013
away_________
1.0080884484115678
Yhat R2: 0.09654
Yhat MedAE: 0.04202
Yhat MeanAE: 0.05031
2014
away_________
1.0008688430516848
Yhat R2: 0.09353
Yhat MedAE: 0.04418
Yhat MeanAE: 0.05173
Coefs b1
[0.35527 0.39786 0.50289 0.33494 0.51074 0.33121 0.39514 0.562   0.49589]
Sum Coefs b1:3.88596
Avg Coefs b1:0.43177
Coefs b2
[0.6477

***
# HOME 3 Make

In [11]:
TRTR = pandas.read_csv("S_Full_HoAw_" + str(startyear) + "_" + str(endyear) + ".csv")
TRTR = TRTR.loc[TRTR['GameNum'] >= 25].dropna()

coefs_b1 = []
coefs_b2 = []
for year in range(startyear, endyear + 1):
    print (year)
    T3make = copy.deepcopy(TRTR.loc[TRTR['Season'] == year])
    home_feats = T3make.loc[:,['home.GG.avg.prob_3make', 'away.BG.avg.prob_3make']]
    home_tar = T3make.loc[:,['home.GG.curr.prob_3make']]
    home_Model = sklearn.linear_model.LinearRegression(fit_intercept = False).fit(home_feats, home_tar )
    T3make['pred'] = home_Model.predict(home_feats)
    print("HOME_________")
    #print(home_Model.coef_)
    coefs_b1 = coefs_b1 + [home_Model.coef_[0][0]]
    coefs_b2 = coefs_b2 + [home_Model.coef_[0][1]]
    print(sum(sum(home_Model.coef_)))
    #print ("F1 R2: " + str(np.round(sklearn.metrics.r2_score(home_tar,T3make.loc[:,['home.GG.avg.prob_3make']]),5)))
    #print ("F2 R2: " + str((np.round(sklearn.metrics.r2_score(home_tar,T3make.loc[:,['away.BG.avg.prob_3make']]),5))))
    print ("Yhat R2: " + str((np.round(sklearn.metrics.r2_score(home_tar, T3make['pred']),5))))
    print ("Yhat MedAE: " + str((np.round(sklearn.metrics.median_absolute_error(home_tar, T3make['pred']),5))))
    print ("Yhat MeanAE: " + str((np.round(sklearn.metrics.mean_absolute_error(home_tar, T3make['pred']),5))))
print("Coefs b1")
print(np.round(coefs_b1,5))
print("Sum Coefs b1:" + str(np.round(np.sum(coefs_b1),5)))
print("Avg Coefs b1:" + str(np.round(np.sum(coefs_b1) / (endyear - startyear + 1),5)))
print("Coefs b2")
print(np.round(coefs_b2,5))
print("Sum Coefs b2:" + str(np.round(sum(coefs_b2),5)))
print("Avg Coefs b2:" + str(np.round(np.sum(coefs_b2) / (endyear - startyear + 1),5)))
print("Avg b1 + b2 Coefs:" + str(np.round((np.sum(coefs_b2) + np.sum(coefs_b1)) / ((endyear - startyear + 1)),5)))


2006
HOME_________
1.008943265191407
Yhat R2: -0.00078
Yhat MedAE: 0.08682
Yhat MeanAE: 0.10204
2007
HOME_________
1.0249713375264586
Yhat R2: -0.0098
Yhat MedAE: 0.08497
Yhat MeanAE: 0.10015
2008
HOME_________
1.0145567009389254
Yhat R2: 0.02097
Yhat MedAE: 0.07927
Yhat MeanAE: 0.09752
2009
HOME_________
1.0306966654943346
Yhat R2: -0.00167
Yhat MedAE: 0.07845
Yhat MeanAE: 0.09475
2010
HOME_________
1.014036885210312
Yhat R2: 0.00547
Yhat MedAE: 0.07819
Yhat MeanAE: 0.09444
2011
HOME_________
0.9913635094925661
Yhat R2: 0.01453
Yhat MedAE: 0.08011
Yhat MeanAE: 0.09362
2012
HOME_________
0.9920487923485034
Yhat R2: -0.00213
Yhat MedAE: 0.07504
Yhat MeanAE: 0.0929
2013
HOME_________
1.0251591126666928
Yhat R2: 0.01233
Yhat MedAE: 0.07268
Yhat MeanAE: 0.08874
2014
HOME_________
0.9987222733862688
Yhat R2: 0.01077
Yhat MedAE: 0.06881
Yhat MeanAE: 0.08458
Coefs b1
[0.53995 0.50162 0.73932 0.64184 0.45448 0.54549 0.65186 0.67735 0.70699]
Sum Coefs b1:5.45889
Avg Coefs b1:0.60654
Coefs b2
[0

***
# Away 3Make

In [12]:
TRTR = pandas.read_csv("S_Full_HoAw_" + str(startyear) + "_" + str(endyear) + ".csv")
TRTR = TRTR.loc[TRTR['GameNum'] >= 25].dropna()

coefs_b1 = []
coefs_b2 = []
for year in range(startyear, endyear + 1):
    print (year)
    TFG = copy.deepcopy(TRTR.loc[TRTR['Season'] == year])
    away_feats = TFG.loc[:,['away.GG.avg.prob_3make', 'home.BG.avg.prob_3make']]
    away_tar = TFG.loc[:,['away.GG.curr.prob_3make']]
    away_Model = sklearn.linear_model.LinearRegression(fit_intercept = False).fit(away_feats, away_tar )
    TFG['pred'] = away_Model.predict(away_feats)
    print("away_________")
    #print(away_Model.coef_)
    coefs_b1 = coefs_b1 + [away_Model.coef_[0][0]]
    coefs_b2 = coefs_b2 + [away_Model.coef_[0][1]]
    print(sum(sum(away_Model.coef_)))
    #print ("F1 R2: " + str(np.round(sklearn.metrics.r2_score(away_tar,TFG.loc[:,['away.GG.avg.prob_3make']]),5)))
    #print ("F2 R2: " + str((np.round(sklearn.metrics.r2_score(away_tar,TFG.loc[:,['away.BG.avg.prob_3make']]),5))))
    print ("Yhat R2: " + str((np.round(sklearn.metrics.r2_score(away_tar, TFG['pred']),5))))
    print ("Yhat MedAE: " + str((np.round(sklearn.metrics.median_absolute_error(away_tar, TFG['pred']),5))))
    print ("Yhat MeanAE: " + str((np.round(sklearn.metrics.mean_absolute_error(away_tar, TFG['pred']),5))))
print("Coefs b1")
print(np.round(coefs_b1,5))
print("Sum Coefs b1:" + str(np.round(np.sum(coefs_b1),5)))
print("Avg Coefs b1:" + str(np.round(np.sum(coefs_b1) / (endyear - startyear + 1),5)))
print("Coefs b2")
print(np.round(coefs_b2,5))
print("Sum Coefs b2:" + str(np.round(sum(coefs_b2),5)))
print("Avg Coefs b2:" + str(np.round(np.sum(coefs_b2) / (endyear - startyear + 1),5)))
print("Avg b1 + b2 Coefs:" + str(np.round((np.sum(coefs_b2) + np.sum(coefs_b1)) / ((endyear - startyear + 1)),5)))

2006
away_________
0.9990369675202878
Yhat R2: -0.0044
Yhat MedAE: 0.07865
Yhat MeanAE: 0.09865
2007
away_________
1.0046608267210524
Yhat R2: -0.00061
Yhat MedAE: 0.0812
Yhat MeanAE: 0.0979
2008
away_________
0.9994933056466122
Yhat R2: 0.00339
Yhat MedAE: 0.07826
Yhat MeanAE: 0.09483
2009
away_________
0.9906582767024892
Yhat R2: 0.00283
Yhat MedAE: 0.08103
Yhat MeanAE: 0.09557
2010
away_________
1.007592501012041
Yhat R2: -0.01033
Yhat MedAE: 0.0734
Yhat MeanAE: 0.094
2011
away_________
0.9635650826001706
Yhat R2: 0.00559
Yhat MedAE: 0.07934
Yhat MeanAE: 0.0892
2012
away_________
0.9889232148858684
Yhat R2: 0.01755
Yhat MedAE: 0.07225
Yhat MeanAE: 0.09129
2013
away_________
0.9693682926022504
Yhat R2: 0.00607
Yhat MedAE: 0.07231
Yhat MeanAE: 0.08855
2014
away_________
1.000423239275945
Yhat R2: -0.00218
Yhat MedAE: 0.07525
Yhat MeanAE: 0.08649
Coefs b1
[0.53094 0.34769 0.3015  0.48834 0.5275  0.61513 0.42254 0.53868 0.49064]
Sum Coefs b1:4.26297
Avg Coefs b1:0.47366
Coefs b2
[0.4680

***
# HOME DRB

In [13]:
TRTR = pandas.read_csv("S_Full_HoAw_" + str(startyear) + "_" + str(endyear) + ".csv")
TRTR = TRTR.loc[TRTR['GameNum'] >= 25].dropna()

coefs_b1 = []
coefs_b2 = []
for year in range(startyear, endyear + 1):
    print (year)
    TDRB = copy.deepcopy(TRTR.loc[TRTR['Season'] == year])
    home_feats = TDRB.loc[:,['home.GG.avg.prob_DRB', 'away.BG.avg.prob_DRB']]
    home_tar = TDRB.loc[:,['home.GG.curr.prob_DRB']]
    home_Model = sklearn.linear_model.LinearRegression(fit_intercept = False).fit(home_feats, home_tar )
    TDRB['pred'] = home_Model.predict(home_feats)
    print("HOME_________")
    #print(home_Model.coef_)
    coefs_b1 = coefs_b1 + [home_Model.coef_[0][0]]
    coefs_b2 = coefs_b2 + [home_Model.coef_[0][1]]
    print(sum(sum(home_Model.coef_)))
    #print ("F1 R2: " + str(np.round(sklearn.metrics.r2_score(home_tar,TDRB.loc[:,['home.GG.avg.prob_DRB']]),5)))
    #print ("F2 R2: " + str((np.round(sklearn.metrics.r2_score(home_tar,TDRB.loc[:,['away.BG.avg.prob_DRB']]),5))))
    print ("Yhat R2: " + str((np.round(sklearn.metrics.r2_score(home_tar, TDRB['pred']),5))))
    print ("Yhat MedAE: " + str((np.round(sklearn.metrics.median_absolute_error(home_tar, TDRB['pred']),5))))
    print ("Yhat MeanAE: " + str((np.round(sklearn.metrics.mean_absolute_error(home_tar, TDRB['pred']),5))))
print("Coefs b1")
print(np.round(coefs_b1,5))
print("Sum Coefs b1:" + str(np.round(np.sum(coefs_b1),5)))
print("Avg Coefs b1:" + str(np.round(np.sum(coefs_b1) / (endyear - startyear + 1),5)))
print("Coefs b2")
print(np.round(coefs_b2,5))
print("Sum Coefs b2:" + str(np.round(sum(coefs_b2),5)))
print("Avg Coefs b2:" + str(np.round(np.sum(coefs_b2) / (endyear - startyear + 1),5)))
print("Avg b1 + b2 Coefs:" + str(np.round((np.sum(coefs_b2) + np.sum(coefs_b1)) / ((endyear - startyear + 1)),5)))


2006
HOME_________
1.0235044452077386
Yhat R2: 0.10221
Yhat MedAE: 0.05125
Yhat MeanAE: 0.06001
2007
HOME_________
1.0147169076019062
Yhat R2: 0.0945
Yhat MedAE: 0.04922
Yhat MeanAE: 0.05867
2008
HOME_________
1.0161813068583305
Yhat R2: 0.10198
Yhat MedAE: 0.04754
Yhat MeanAE: 0.05724
2009
HOME_________
1.0119402670771045
Yhat R2: 0.08074
Yhat MedAE: 0.05148
Yhat MeanAE: 0.05851
2010
HOME_________
1.0149462398720623
Yhat R2: 0.09299
Yhat MedAE: 0.04922
Yhat MeanAE: 0.05758
2011
HOME_________
1.0038143199059426
Yhat R2: 0.07975
Yhat MedAE: 0.05464
Yhat MeanAE: 0.06263
2012
HOME_________
1.00656673886672
Yhat R2: 0.09178
Yhat MedAE: 0.05222
Yhat MeanAE: 0.06008
2013
HOME_________
1.0177920452948024
Yhat R2: 0.08603
Yhat MedAE: 0.04624
Yhat MeanAE: 0.05639
2014
HOME_________
1.0108559212974837
Yhat R2: 0.11425
Yhat MedAE: 0.04736
Yhat MeanAE: 0.05639
Coefs b1
[0.36942 0.39742 0.29023 0.58181 0.33968 0.35596 0.39837 0.28309 0.30227]
Sum Coefs b1:3.31826
Avg Coefs b1:0.3687
Coefs b2
[0.654

***
# Away DRB

In [14]:
TRTR = pandas.read_csv("S_Full_HoAw_" + str(startyear) + "_" + str(endyear) + ".csv")
TRTR = TRTR.loc[TRTR['GameNum'] >= 25].dropna()

coefs_b1 = []
coefs_b2 = []
for year in range(startyear, endyear + 1):
    print (year)
    TFG = copy.deepcopy(TRTR.loc[TRTR['Season'] == year])
    away_feats = TFG.loc[:,['away.GG.avg.prob_DRB', 'home.BG.avg.prob_DRB']]
    away_tar = TFG.loc[:,['away.GG.curr.prob_DRB']]
    away_Model = sklearn.linear_model.LinearRegression(fit_intercept = False).fit(away_feats, away_tar )
    TFG['pred'] = away_Model.predict(away_feats)
    print("away_________")
    #print(away_Model.coef_)
    coefs_b1 = coefs_b1 + [away_Model.coef_[0][0]]
    coefs_b2 = coefs_b2 + [away_Model.coef_[0][1]]
    print(sum(sum(away_Model.coef_)))
    #print ("F1 R2: " + str(np.round(sklearn.metrics.r2_score(away_tar,TFG.loc[:,['away.GG.avg.prob_DRB']]),5)))
    #print ("F2 R2: " + str((np.round(sklearn.metrics.r2_score(away_tar,TFG.loc[:,['away.BG.avg.prob_DRB']]),5))))
    print ("Yhat R2: " + str((np.round(sklearn.metrics.r2_score(away_tar, TFG['pred']),5))))
    print ("Yhat MedAE: " + str((np.round(sklearn.metrics.median_absolute_error(away_tar, TFG['pred']),5))))
    print ("Yhat MeanAE: " + str((np.round(sklearn.metrics.mean_absolute_error(away_tar, TFG['pred']),5))))
print("Coefs b1")
print(np.round(coefs_b1,5))
print("Sum Coefs b1:" + str(np.round(np.sum(coefs_b1),5)))
print("Avg Coefs b1:" + str(np.round(np.sum(coefs_b1) / (endyear - startyear + 1),5)))
print("Coefs b2")
print(np.round(coefs_b2,5))
print("Sum Coefs b2:" + str(np.round(sum(coefs_b2),5)))
print("Avg Coefs b2:" + str(np.round(np.sum(coefs_b2) / (endyear - startyear + 1),5)))
print("Avg b1 + b2 Coefs:" + str(np.round((np.sum(coefs_b2) + np.sum(coefs_b1)) / ((endyear - startyear + 1)),5)))

2006
away_________
0.9950164170796219
Yhat R2: 0.08865
Yhat MedAE: 0.05457
Yhat MeanAE: 0.06207
2007
away_________
0.9988510459512705
Yhat R2: 0.0809
Yhat MedAE: 0.05081
Yhat MeanAE: 0.06056
2008
away_________
0.9923420953522173
Yhat R2: 0.08957
Yhat MedAE: 0.05077
Yhat MeanAE: 0.05954
2009
away_________
0.9949120876955242
Yhat R2: 0.09393
Yhat MedAE: 0.05031
Yhat MeanAE: 0.05966
2010
away_________
1.0023109210972347
Yhat R2: 0.08152
Yhat MedAE: 0.04646
Yhat MeanAE: 0.05579
2011
away_________
0.9976917824966754
Yhat R2: 0.04962
Yhat MedAE: 0.049
Yhat MeanAE: 0.05794
2012
away_________
0.9911736822400302
Yhat R2: 0.13018
Yhat MedAE: 0.0506
Yhat MeanAE: 0.05802
2013
away_________
1.0010917858277184
Yhat R2: 0.1394
Yhat MedAE: 0.04993
Yhat MeanAE: 0.05942
2014
away_________
0.9974895002600312
Yhat R2: 0.09772
Yhat MedAE: 0.04834
Yhat MeanAE: 0.05885
Coefs b1
[0.51458 0.34978 0.28828 0.41213 0.52947 0.43638 0.04633 0.15983 0.34123]
Sum Coefs b1:3.07801
Avg Coefs b1:0.342
Coefs b2
[0.48044 

***
# HOME Plays

In [15]:
TRTR = pandas.read_csv("S_Full_HoAw_" + str(startyear) + "_" + str(endyear) + ".csv")
TRTR = TRTR.loc[TRTR['GameNum'] >= 25].dropna()

coefs_b1 = []
coefs_b2 = []
for year in range(startyear, endyear + 1):
    print (year)
    TDRB = copy.deepcopy(TRTR.loc[TRTR['Season'] == year])
    home_feats = TDRB.loc[:,['home.GG.avg.plays', 'away.BG.avg.plays']]
    home_tar = TDRB.loc[:,['home.GG.curr.plays']]
    home_Model = sklearn.linear_model.LinearRegression(fit_intercept = False).fit(home_feats, home_tar )
    TDRB['pred'] = home_Model.predict(home_feats)
    print("HOME_________")
    #print(home_Model.coef_)
    coefs_b1 = coefs_b1 + [home_Model.coef_[0][0]]
    coefs_b2 = coefs_b2 + [home_Model.coef_[0][1]]
    print(sum(sum(home_Model.coef_)))
    #print ("F1 R2: " + str(np.round(sklearn.metrics.r2_score(home_tar,TDRB.loc[:,['home.GG.avg.plays']]),5)))
    #print ("F2 R2: " + str((np.round(sklearn.metrics.r2_score(home_tar,TDRB.loc[:,['away.BG.avg.plays']]),5))))
    print ("Yhat R2: " + str((np.round(sklearn.metrics.r2_score(home_tar, TDRB['pred']),5))))
    print ("Yhat MedAE: " + str((np.round(sklearn.metrics.median_absolute_error(home_tar, TDRB['pred']),5))))
    print ("Yhat MeanAE: " + str((np.round(sklearn.metrics.mean_absolute_error(home_tar, TDRB['pred']),5))))
print("Coefs b1")
print(np.round(coefs_b1,5))
print("Sum Coefs b1:" + str(np.round(np.sum(coefs_b1),5)))
print("Avg Coefs b1:" + str(np.round(np.sum(coefs_b1) / (endyear - startyear + 1),5)))
print("Coefs b2")
print(np.round(coefs_b2,5))
print("Sum Coefs b2:" + str(np.round(sum(coefs_b2),5)))
print("Avg Coefs b2:" + str(np.round(np.sum(coefs_b2) / (endyear - startyear + 1),5)))
print("Avg b1 + b2 Coefs:" + str(np.round((np.sum(coefs_b2) + np.sum(coefs_b1)) / ((endyear - startyear + 1)),5)))


2006
HOME_________
0.999061220181377
Yhat R2: 0.18034
Yhat MedAE: 4.22936
Yhat MeanAE: 5.1747
2007
HOME_________
0.9971905031075908
Yhat R2: 0.19266
Yhat MedAE: 4.50853
Yhat MeanAE: 5.46327
2008
HOME_________
0.9985536405833011
Yhat R2: 0.28948
Yhat MedAE: 4.72251
Yhat MeanAE: 5.51257
2009
HOME_________
0.9990483812567721
Yhat R2: 0.2836
Yhat MedAE: 4.42776
Yhat MeanAE: 5.32178
2010
HOME_________
0.9975062818145081
Yhat R2: 0.23674
Yhat MedAE: 4.19185
Yhat MeanAE: 4.92456
2011
HOME_________
0.9959852295902172
Yhat R2: 0.21991
Yhat MedAE: 4.44668
Yhat MeanAE: 5.26521
2012
HOME_________
1.0005948436787415
Yhat R2: 0.12603
Yhat MedAE: 4.13905
Yhat MeanAE: 5.02914
2013
HOME_________
0.9959749915515166
Yhat R2: 0.18279
Yhat MedAE: 4.34425
Yhat MeanAE: 5.03062
2014
HOME_________
0.998142805503308
Yhat R2: 0.21606
Yhat MedAE: 4.56607
Yhat MeanAE: 5.4908
Coefs b1
[0.52243 0.53594 0.47152 0.47885 0.44756 0.5231  0.52453 0.41178 0.54914]
Sum Coefs b1:4.46484
Avg Coefs b1:0.49609
Coefs b2
[0.4766

***
# Away Plays

In [16]:
TRTR = pandas.read_csv("S_Full_HoAw_" + str(startyear) + "_" + str(endyear) + ".csv")
TRTR = TRTR.loc[TRTR['GameNum'] >= 25].dropna()

coefs_b1 = []
coefs_b2 = []
for year in range(startyear, endyear + 1):
    print (year)
    TFG = copy.deepcopy(TRTR.loc[TRTR['Season'] == year])
    away_feats = TFG.loc[:,['away.GG.avg.plays', 'home.BG.avg.plays']]
    away_tar = TFG.loc[:,['away.GG.curr.plays']]
    away_Model = sklearn.linear_model.LinearRegression(fit_intercept = False).fit(away_feats, away_tar )
    TFG['pred'] = away_Model.predict(away_feats)
    print("away_________")
    #print(away_Model.coef_)
    coefs_b1 = coefs_b1 + [away_Model.coef_[0][0]]
    coefs_b2 = coefs_b2 + [away_Model.coef_[0][1]]
    print(sum(sum(away_Model.coef_)))
    #print ("F1 R2: " + str(np.round(sklearn.metrics.r2_score(away_tar,TFG.loc[:,['away.GG.avg.plays']]),5)))
    #print ("F2 R2: " + str((np.round(sklearn.metrics.r2_score(away_tar,TFG.loc[:,['away.BG.avg.plays']]),5))))
    print ("Yhat R2: " + str((np.round(sklearn.metrics.r2_score(away_tar, TFG['pred']),5))))
    print ("Yhat MedAE: " + str((np.round(sklearn.metrics.median_absolute_error(away_tar, TFG['pred']),5))))
    print ("Yhat MeanAE: " + str((np.round(sklearn.metrics.mean_absolute_error(away_tar, TFG['pred']),5))))
print("Coefs b1")
print(np.round(coefs_b1,5))
print("Sum Coefs b1:" + str(np.round(np.sum(coefs_b1),5)))
print("Avg Coefs b1:" + str(np.round(np.sum(coefs_b1) / (endyear - startyear + 1),5)))
print("Coefs b2")
print(np.round(coefs_b2,5))
print("Sum Coefs b2:" + str(np.round(sum(coefs_b2),5)))
print("Avg Coefs b2:" + str(np.round(np.sum(coefs_b2) / (endyear - startyear + 1),5)))
print("Avg b1 + b2 Coefs:" + str(np.round((np.sum(coefs_b2) + np.sum(coefs_b1)) / ((endyear - startyear + 1)),5)))

2006
away_________
0.9929733441326374
Yhat R2: 0.20054
Yhat MedAE: 4.1696
Yhat MeanAE: 5.18524
2007
away_________
0.9940948871437949
Yhat R2: 0.19026
Yhat MedAE: 4.38202
Yhat MeanAE: 5.5588
2008
away_________
0.9937636539921313
Yhat R2: 0.29411
Yhat MedAE: 4.31163
Yhat MeanAE: 5.26089
2009
away_________
0.9971855765450302
Yhat R2: 0.30082
Yhat MedAE: 4.41282
Yhat MeanAE: 5.29791
2010
away_________
0.9943166630823708
Yhat R2: 0.22279
Yhat MedAE: 4.19219
Yhat MeanAE: 5.02595
2011
away_________
0.9965876527012695
Yhat R2: 0.23591
Yhat MedAE: 4.37312
Yhat MeanAE: 5.21261
2012
away_________
0.9973738105125706
Yhat R2: 0.14659
Yhat MedAE: 4.01901
Yhat MeanAE: 4.97399
2013
away_________
0.9939601505904265
Yhat R2: 0.156
Yhat MedAE: 4.32073
Yhat MeanAE: 5.16944
2014
away_________
0.9967278811066742
Yhat R2: 0.21625
Yhat MedAE: 4.51263
Yhat MeanAE: 5.41262
Coefs b1
[0.43358 0.38165 0.39652 0.39331 0.39219 0.5395  0.71267 0.40257 0.54483]
Sum Coefs b1:4.19683
Avg Coefs b1:0.46631
Coefs b2
[0.559